server:
  port: 38090
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
custom:
  config:
#    dagentparentpath: /home/alipms/
    dagentparentpath: D:\\home\\alipms

    cmd3path: /home/alipms/cmdsh3
  logging:
    config: classpath:logback-spring.xml
